[package]
name = "scalar-expr"
license.workspace = true
description = "validation expressions for scalar cms"
authors = ["drac <drac@drac.gay>"]
version = "0.2.0"
edition = "2024"

[dependencies]
scalar-expr-macro = { version = "0.2", path = "../scalar-expr-macro" }
serde_json = {workspace = true}

[lints]
workspace = true
